function List() {};
module.exports = List;

List.prototype.init = function() {};
List.prototype.size = function() {};
List.prototype.addStart = function() {};
List.prototype.addEnd = function() {};
List.prototype.delStart = function() {};
List.prototype.delEnd = function() {};
List.prototype.delPos = function() {};
List.prototype.get = function() {};
List.prototype.set = function() {};
List.prototype.toString = function() {};
List.prototype.get = function() {};
List.prototype.min = function() {};
List.prototype.max = function() {};
List.prototype.sort = function() {};
List.prototype.maxIndex = function() {};
List.prototype.minIndex = function() {};
List.prototype.reverse = function() {};
List.prototype.halfReverse = function() {};
List.prototype.addPos = function() {};
List.prototype.toArray = function() {};